CarAdvisor/app/__init__.py
# Import the create_app function and main_bp blueprint from the CarAdvisor.app.routes module
from CarAdvisor.app.routes import create_app, main_bp

# Create the Flask application using the create_app function
app = create_app()

# Register the main_bp blueprint with the Flask application
app.register_blueprint(main_bp)

CarAdvisor/app/routes.py
# Import necessary modules and functions from Flask
from flask import Flask, Blueprint, render_template, request, jsonify, redirect, url_for
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
from functools import wraps
import sqlite3
import hashlib

# Import custom functionalities from the 'utils' module
from CarAdvisor.utils.carRecommendation import recommended_cars
from CarAdvisor.utils.pricePrediction import price_prediction

# Create a Blueprint to organize routes and views
main_bp = Blueprint('main', __name__, static_folder='static', template_folder='templates')

# Function to create the Flask application instance
def create_app():
    app = Flask(__name__, instance_relative_config=True)
    app.secret_key = '8sdf8932hjksdf!@#$%^&*()_+'

    # Initialize Flask-Login
    login_manager = LoginManager()
    login_manager.init_app(app)

    # Define a User class for Flask-Login
    class User(UserMixin):
        def __init__(self, user_id, username, is_admin = False):
            self.id = user_id
            self.username = username
            self.is_admin = is_admin

    # Database connection function
    def get_db_connection():
        conn = sqlite3.connect('mainDB.db')
        conn.row_factory = sqlite3.Row
        return conn
    
    # User loader function required by Flask-Login
    @login_manager.user_loader
    def load_user(user_id):
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM users WHERE userid = ?", (user_id,))
        user_data = cursor.fetchone()
        conn.close()
        if user_data:
            return User(user_data['userid'], user_data['username'], user_data['is_admin'])
        return None
    
    # Decorator to restrict access to admin routes
    def admin_required(view):
        @wraps(view)
        def wrapped_view(*args, **kwargs):
            if not current_user.is_admin:
                return render_template('unauthorized.html')
            return view(*args, **kwargs)
        return wrapped_view
    
    # admin route
    @main_bp.route('/dashboard')
    @login_required
    @admin_required
    def admin_dashboard():
        users = get_user_list()
        return render_template('admin_dashboard.html', users = users)
    
    # user deletion
    @main_bp.route('/admin/delete-user/<int:user_id>', methods=['POST'])
    @login_required
    @admin_required
    def delete_user(user_id):
        # Delete the user from the database
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute("DELETE FROM users WHERE userid = ?", (user_id,))
        conn.commit()
        conn.close()
        return redirect(url_for('main.admin_dashboard'))
    
    # get user list
    def get_user_list():
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM users")
        users = cursor.fetchall()
        conn.close()
        return users
    
    # user registration
    @main_bp.route('/register', methods=['GET', 'POST'])
    def user_register():
        if request.method == 'POST':
            fullname = request.form['fullname']
            email = request.form['email']
            username = request.form['username'].lower()
            password = hashlib.sha256(request.form['password'].encode()).hexdigest()

            conn = get_db_connection()
            cursor = conn.cursor()
            try:
                cursor.execute("INSERT INTO users (email, name, username, password) VALUES (?, ?, ?, ?)", (email, fullname, username, password))
                conn.commit()
                conn.close()
                return render_template('user_register.html', success_message='Account Created Successfully!')
            except sqlite3.IntegrityError:
                conn.close()
                return render_template('user_register.html', error_message='Username or email already exists!')

        return render_template('user_register.html')
    
    # user login
    @main_bp.route('/login', methods=['GET', 'POST'])
    def user_login():
        if request.method == 'POST':
            username = request.form['username'].lower()
            password = hashlib.sha256(request.form['password'].encode()).hexdigest()

            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM users WHERE username = ? AND password = ?", (username, password))
            user = cursor.fetchone()
            conn.close()

            if user:
                user_obj = User(user['userid'], user['username'], user['is_admin'])
                login_user(user_obj)

                if user['is_admin']==1:
                    return redirect(url_for('main.admin_dashboard'))
                return redirect(url_for('main.home'))
            else:
                return render_template('user_login.html', error_message='Invalid username or password')

        return render_template('user_login.html')
    
    # Logout
    @main_bp.route('/logout')
    @login_required
    def logout():
        logout_user()
        return redirect(url_for('main.home'))


    # Home Page
    @main_bp.route('/')
    def home():
        return render_template('index.html')
    
    # Car recommendation
    @main_bp.route('/recommend', methods=['GET', 'POST'])
    @login_required
    def recommend_cars():
        error_message = None
        if request.method == 'POST':
            features = [request.form.get(feature) for feature in ['made', 'color_group', 'type_group', 'price_range', 'transmission']]
            features[1] = features[1].lower()
            features[4] = features[4].lower()
            features[3] = tuple(map(int, features[3].split('-')))
            try:
                cars = recommended_cars(tuple(features))
            except Exception as e:
                error_message = "Invalid input!"
            if error_message:
                return render_template('recommend.html', error_message = error_message)
            else:
                return render_template('recommend.html',cars = cars, features = features)
        return render_template('recommend.html')
    
    # Car price prediction
    @main_bp.route('/predict', methods=['GET', 'POST'])
    @login_required
    def predict_price():
        error_message = None
        if request.method == 'POST':
            features = [request.form.get(feature) for feature in ['year', 'odometer', 'cylinders', 'manufacturer', 'model', 'fuel', 'title_status', 'transmission', 'condition', 'drive', 'type']]
            try:
                predicted_price = price_prediction(features)
            except Exception as e:
                error_message = f"Error: {e}"
            if error_message:
                return render_template('predict.html', error_message = error_message)
            else:
                return render_template('predict.html', predicted_price = predicted_price)
        return render_template('predict.html')
    
    # User feedback for car recommendation
    @main_bp.route('/feedback', methods = ['POST'])
    @login_required
    def feedback_rating():
        if request.method == 'POST':
            rating = int(request.form['inlineRadioOptions'])
            conn = get_db_connection()
            cur = conn.cursor()
            cur.execute("INSERT INTO rec_ratings (ratings) VALUES (?)", (rating,))
            conn.commit()
            cur.close()
        return render_template('recommend.html', rating = rating)
    
    # count feedback rating
    @main_bp.route('/rating-count')
    @login_required
    def rating_count():
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("SELECT ratings FROM rec_ratings")
        ratings = cur.fetchall()
        ratings_count = {}
        for rating in ratings:
            rating = rating[0]
            if rating in ratings_count:
                ratings_count[rating] += 1
            else:
                ratings_count[rating] = 1
        return jsonify(ratings_count)
        
    # show privacy policy page
    @main_bp.route('/privacy-policy')
    def privacy():
        return render_template('privacy_policy.html')

    # show terms and conditions page
    @main_bp.route('/terms-and-conditions')
    def terms():
        return render_template('terms_conditions.html')
    
    # Return the Flask app instance
    return app

CarAdvisor/app/templates/admin_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car Advisor - Used Car Price Prediction and Recommendation</title>
    <link rel="icon" type="image/x-icon" href="../static/favicon.svg">
    <!-- Add the Bootstrap CSS link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>
<body>
    <div class="container bg-body-tertiary rounded-3">
      {% if current_user.is_authenticated %}
      <div class="container d-flex flex-wrap">
        <ul class="nav me-auto">
          <li class="nav-item">Welcome, {{ current_user.username }}</li>
        </ul>
        <ul class="nav">
          <li class="nav-item">
            <a href="logout" style="text-decoration: none;"> Logout
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
              </svg>
            </a>
          </li>
        </ul>
      </div>
      {% endif %}
        <!-- hero section with image -->
        <div class="container col-xxl-8 px-4 py-5">
            <table class="table table-hover table-bordered caption-top">
                <caption>User List</caption>
                <thead class="table-light">
                    <tr>
                        <th class="col">User ID</th>
                        <th class="col">Name</th>
                        <th class="col">Email</th>
                        <th class="col">Username</th>
                        <th class="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    {% if not user.is_admin %}
                    <tr>
                        <td>{{ user.userid }}</td>
                        <td>{{ user.name }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.username }}</td>
                        <td>
                            <form action="{{ url_for('main.delete_user', user_id=user.userid) }}" method="post">
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- end hero -->
        
        <!-- footer section -->
        <div class="container">
            <footer class="py-3 my-4">
              <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="/" class="nav-link px-2 text-body-secondary">Home</a></li>
                <li class="nav-item"><a href="mailto:arefins106@gmail.com" class="nav-link px-2 text-body-secondary">Contact</a></li>
                <li class="nav-item"><a href="/privacy-policy" class="nav-link px-2 text-body-secondary">Privacy Policy</a></li>
                <li class="nav-item"><a href="/terms-and-conditions" class="nav-link px-2 text-body-secondary">Terms and Conditions</a></li>
              </ul>
              <p class="text-center text-body-secondary">&copy; 2024 Car Advisor. All rights reserved. Developed by <a href="https://github.com/ShamimulArefin" target="_blank">Md Shamimul Arefin</a> &#10084;</p>
            </footer>
        </div>
        <!-- end footer -->
        
    </div>
    <!-- end body -->

    <!-- modal script to preview image -->
    <script>
        $(document).ready(function () {
          $('.img-thumbnail').click(function () {
            var imgSrc = $(this).attr('src');
            $('#previewImage').attr('src', imgSrc);
          });
        });
    </script>
    <!-- Add the Bootstrap JS and Popper.js scripts (required for Bootstrap components) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

CarAdvisor/app/templates/recommend.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="../static/favicon.svg">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <title>Find Your Perfect Car</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            color: #333;
        }
        form {
            margin-top: 20px;
        }
        label {
            margin-right: 10px;
        }
        select {
            margin-right: 10px;
        }
        button {
            padding: 8px 16px;
            font-size: 16px;
        }
        #result-container {
            margin-top: 20px;
        }
    </style>

</head>
<body>
    <div class="container bg-body-tertiary rounded-3">
      <div class="container d-flex flex-wrap">
        <nav aria-label="breadcrumb" class="me-auto">
            <ol class="breadcrumb p-2 bg-body-tertiary rounded-3">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Prediction</li>
            </ol>
        </nav>
        <ul class="nav">
            <li class="nav-item">
                <a href="logout" style="text-decoration: none;"> Logout
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
                      <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                      </svg>
                  </a>
            </li>
        </ul>
      </div>
        <!-- hero section -->
        <div class="px-4 py-3 my-2 text-center">
            <a href="/"><img class="d-block mx-auto mb-3" src="../static/carrecommend.png" alt="" width="80" height="80"></a>
            <h1 class="display-5 fw-bold text-body-emphasis">Find Your Perfect Car</h1>
            <!-- form input area -->
            <div class="row mt-3">
              <div class="col-lg-5 mx-auto">
                <div class="accordion" id="accordionExample">
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                        Details of Color types in Color Group!
                      </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                      <div class="accordion-body">
                        <p><b>Light Color: </b>white, silver, yellow, orange, green, custom</p>
                        <p><b>Dark Color: </b>black, red, blue, purple, grey, brown</p>
                      </div>
                    </div>
                  </div>
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingTwo">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Details of Car types in Type Group!
                      </button>
                    </h2>
                    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                      <div class="accordion-body">
                        <p><b>luxury_small: </b>sedan, convertible, coupe, hatchback, others</p>
                        <p><b>luxury_large: </b>SUV, Wagon</p>
                        <p><b>non-luxury_small: </b>pickup, truck, offroad</p>
                        <p><b>non-luxury_large: </b>van, mini-van, bus</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="rating mt-2 mb-3">
                  <legend>Give Rating to this recommendation system for research works!
                  </legend>
                  <form action="{{url_for('main.feedback_rating')}}" method="POST" class="g-3">
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="1">
                      <label class="form-check-label" for="inlineRadio1">1⭐️</label>
                    </div>
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="2">
                      <label class="form-check-label" for="inlineRadio2">2⭐️</label>
                    </div>
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="3">
                      <label class="form-check-label" for="inlineRadio3">3⭐️</label>
                    </div>
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio4" value="4">
                      <label class="form-check-label" for="inlineRadio4">4⭐️</label>
                    </div>
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio5" value="5">
                      <label class="form-check-label" for="inlineRadio5">5⭐️</label>
                    </div>
                    <button type="submit" class="btn btn-info px-4 gap-3 ">Submit</button>
                  </form>
                  {% if rating %}
                  <h5>Thanks for your feedback!❤️</h5>
                  {% endif %}
                </div>
              </div>
              <div class="col-lg-1"></div>
            <div class="col-lg-6 mx-auto">
                <form action="{{url_for('main.recommend_cars')}}" method="POST" class="row g-3">
                  <div class="col-md-6">
                    <label for="made" class="form-label">Made</label>
                    <select id="made" class="form-select" name="made" required>
                      <option selected disabled value>Choose...</option>
                      <option>American</option>
                      <option>English</option>
                      <option>German</option>
                      <option>Italian</option>
                      <option>Swedish</option>
                      <option>Japanese</option>
                      <option>Korean</option>
                    </select>
                  </div>
                  <div class="col-md-6">
                    <label for="color_group" class="form-label">Color Group</label>
                    <select id="color_group" class="form-select" name="color_group" required>
                      <option selected disabled value>Choose...</option>
                      <option>Dark Color</option>
                      <option>Light Color</option>
                    </select>
                  </div>
                  <div class="col-md-6">
                    <label for="type_group" class="form-label">Type Group</label>
                    <select id="type_group" class="form-select" name="type_group" required>
                      <option selected disabled value>Choose...</option>
                      <option>non-luxury_small</option>
                      <option>luxury_small</option>
                      <option>luxury_large</option>
                      <option>non-luxury_large</option>
                    </select>
                  </div>
                  <div class="col-md-6">
                    <label for="transmission" class="form-label">Transmission</label>
                    <select id="transmission" class="form-select" name="transmission" required>
                      <option selected disabled value>Choose...</option>
                      <option>Automatic</option>
                      <option>Manual</option>
                      <option>Other</option>
                    </select>
                  </div>
                  <div class="col-md-12">
                      <label for="price_range">Price range($):</label>
                      <input type="text" id="price_range" name="price_range" readonly="" style="border:0; color:#f6931f; font-weight:bold; background: none;">
                    <div id="slider-range"></div>
                  </div>
                    <div class="col-12">
                      <button type="submit" class="btn btn-lg px-4 gap-3 " style="color: white; background-color: #580EEB;">Recommend</button>
                    </div>
                </form>
            </div>
            <!-- form area end -->
            </div>
        </div>
        {% if error_message %}
        <div id="result-container" class="alert alert-info fw-bold" role="alert">
          Error: No cars found in this range!
        </div>
        {% endif %}
        {% if cars %}
        <div id="result-container" class="table-responsive">
            <table class="table table-hover table-bordered caption-top">
              <caption>Recommended Cars similar to Made by '{{features[0]}}', Color type '{{features[1]}}', Car Type '{{features[2]}}', Transmission '{{features[4]}}', and Price Range ${{features[3]}}</caption>
                <thead class="table-light" style="border: #580EEB;">
                  <tr>
                    {% for title in cars[1]%}
                    <th scope="col">{{title}}</th>
                    {% endfor %}
                  </tr>
                </thead>
                <tbody>
                    {% for index, row in cars[0].iterrows() %}
                  <tr>
                    {% for value in row %}
                    <td>{{value}}</td>
                    {% endfor %}
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
        {% endif %}

        <!-- contribution section -->
        <div class="container my-5">
          <a href="contribute" style="color: silver; text-decoration: none;">
          <div class="p-5 text-center rounded-3" style="background-image: url(../static/contribution_image.png); background-size: cover; background-position: center;">
            <h1 class="mb-3">.</h1>
            <p class="lead">.</p>
          </div></a>
        </div>
        <!-- contribution end -->
        <!-- footer section -->
        <div class="container">
            <footer class="py-3 my-4">
              <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="" class="nav-link px-2 text-body-secondary">Home</a></li>
                <li class="nav-item"><a href="mailto:arefins106@gmail.com" class="nav-link px-2 text-body-secondary">Contact</a></li>
                <li class="nav-item"><a href="/privacy-policy" class="nav-link px-2 text-body-secondary">Privacy Policy</a></li>
                <li class="nav-item"><a href="/terms-and-conditions" class="nav-link px-2 text-body-secondary">Terms and Conditions</a></li>
              </ul>
              <p class="text-center text-body-secondary">&copy; 2024 Car Advisor. All rights reserved. Developed by <a href="https://github.com/ShamimulArefin" target="_blank">Md Shamimul Arefin</a> &#10084;</p>
            </footer>
        </div>
        <!-- end footer -->
    </div>

    <script>
      $( function() {
        $( "#slider-range" ).slider({
          range: true,
          min: 1000,
          max: 195000,
          values: [ 5000, 30000 ],
          slide: function( event, ui ) {
            $( "#price_range" ).val(ui.values[ 0 ] + "-" + ui.values[ 1 ] );
          }
        });
        $( "#price_range" ).val($( "#slider-range" ).slider( "values", 0 ) + "-" +$( "#slider-range" ).slider( "values", 1 ) );
      } );
    </script>
</body>
</html>

CarAdvisor/app/templates/user_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="../static/favicon.svg">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Create Your Account - Car Advisor</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            color: #333;
        }
        form {
            margin-top: 20px;
        }
        label {
            margin-right: 10px;
        }
        select {
            margin-right: 10px;
        }
        button {
            padding: 8px 16px;
            font-size: 16px;
        }
        #result-container {
            margin-top: 30px;
        }
    </style>


</head>
<body>
    <div class="container bg-body-tertiary rounded-3">
        <!-- hero section -->
        <div class="px-4 py-5 my-2 text-center">
            <a href="/"><img class="d-block mx-auto mb-3" src="../static/favicon.svg" alt="" width="72" height="72"></a>
            <h1 class="display-5 fw-bold text-body-emphasis">Login to Your Account</h1>
            <!-- form input area -->
            <div class="col-lg-6 mx-auto">
                <form action="{{url_for('main.user_login')}}" method="POST" class="row g-3">
                    <div class="col-md-6">
                        <label for="username" class="form-label">Username</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                    <div class="col-md-6">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                    <div class="col-12">
                      <button type="submit" class="btn btn-lg px-4 gap-3 " style="color: white; background-color: #580EEB;">Login</button>
                    </div>
                </form>
            </div>
            <div id="result-container">
                <h5>Don't have account! <a href="register">Create account here</a></h5>
                {% if error_message %}
                <div class="alert alert-danger fw-bold" role="alert">
                    {{error_message}}
                </div>
                {% endif %}
            </div>
        </div>
        <!-- contribution section -->
        <div class="container my-5">
            <a href="contribute" style="color: silver; text-decoration: none;">
            <div class="p-5 text-center rounded-3" style="background-image: url(../static/contribution_image.png); background-size: cover; background-position: center;">
                <h1 class="mb-3">.</h1>
                <p class="lead">.</p>
            </div></a>
            </div>
            <!-- contribution end -->
            <!-- footer section -->
            <div class="container">
                <footer class="py-3 my-4">
                <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                    <li class="nav-item"><a href="" class="nav-link px-2 text-body-secondary">Home</a></li>
                    <li class="nav-item"><a href="mailto:arefins106@gmail.com" class="nav-link px-2 text-body-secondary">Contact</a></li>
                    <li class="nav-item"><a href="/privacy-policy" class="nav-link px-2 text-body-secondary">Privacy Policy</a></li>
                    <li class="nav-item"><a href="/terms-and-conditions" class="nav-link px-2 text-body-secondary">Terms and Conditions</a></li>
                </ul>
                <p class="text-center text-body-secondary">&copy; 2024 Car Advisor. All rights reserved. Developed by <a href="https://github.com/ShamimulArefin" target="_blank">Md Shamimul Arefin</a> &#10084;</p>
                </footer>
            </div>
            <!-- end footer -->
    </div>
        
</body>
</html>